# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19cGx68RHUFvsTqUFTZqKmn3MCoyKxQnZ
"""

# add these lines in report
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# load the experimental data
xavg = pd.read_csv('data.csv')
npeople = np.array(range(0,5,1))
time = np.array(range(1,11,1))

# fitting data
reg = LinearRegression().fit(npeople.reshape(-1,1),xavg)
xhat = reg.coef_*npeople + reg.intercept_

# plot the experimental data and fitted data
plt.plot(npeople,xavg,'o',npeople,xhat,'r')
plt.xticks(ticks = npeople)